acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns =[
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('port/', include("port.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

port/urls.py
from django.urls import path
from . import views

app_name = "port"
urlpatterns =[
    path('index/', views.index, name="index")
]

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    comment = models.TextField()
    point = models.IntegerField(default=0)
    age = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y/%m")

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/익명이.png"

board/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.subject}"
    
    def summary(self):
        if len(self.content) > 100:
            return f"{self.content[:100]} + ... " 
        return self.content

class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.b}_{self.replyer}"

port/models.py
from django.db import models

# Create your models here.

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User

def update(request):
    if request.method == "POST":
        u = request.user
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        ua = request.POST.get("uage")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        u.username = un
        if up:
            u.set_password(up)
        u.age = ua
        u.comment = uc
        if pi:
            u.pic.delete()
            u.pic = pi
        u.save()
        login(request, u)
        return redirect("acc:profile")



    return render(request, "acc/update.html")

def delete(request):
    ck = request.POST.get("ckpw")
    if check_password(ck, request.user.password):
        request.user.pic.delete()
        request.user.delete()
        return redirect("acc:index")
    else:
        pass # 19일
    # check_password(평문, 비문)  비교해서맞으면 True
    return redirect("acc:profile")

def profile(request):
    return render(request, "acc/profile.html")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        ua = request.POST.get("uage")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        try:
            User.objects.create_user(username=un, password=up, age=ua, comment=uc, pic=pi)
            return redirect("acc:login")
        except:
            pass # 19일차!!
    return render(request, "acc/signup.html")


def logout_user(request):
    logout(request)
    return redirect("acc:login")

# Create your views here.
def index(request):
    return render(request, "acc/index.html")

def login_user(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        pw = request.POST.get("upass")
        user = authenticate(username=un, password=pw)
        if user:
            login(request, user)
            return redirect("acc:index")
        else:
            pass
    return render(request, "acc/login.html")

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
# Create your views here.
from django.utils import timezone


def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == request.user:
        r.delete()
    else:
        pass # 19 일차
    return redirect("board:detail", bpk)





def creply(request, bpk):
    c = request.POST.get("com")
    b = Board.objects.get(id=bpk)
    Reply(b=b, replyer=request.user, comment=c, pubdate=timezone.now()).save()
    return redirect("board:detail", bpk)

def update(request, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer != request.user:
        # 19 일차 메세지
        return redirect("board:index")
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:detail", bpk)
    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        if s and c:
            Board(subject=s, content=c, writer=request.user, pubdate=timezone.now()).save()
            return redirect("board:index")
    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        pass # 19일차
    return redirect("board:index")


def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b": b,
        "rset" : r
    }
    return render(request, "board/detail.html", context)



def index(request):
    b = Board.objects.all()
    context = {
        "bset": b
    }
    return render(request, "board/index.html", context)

port/views.py
from django.shortcuts import render

# Create your views here.

def index (request):
    return render (request, "port/index.html")

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">YUBEEN'S PORTFOLIO </h1>
            <p class="col-md-8 fs-4">PHOTO | VIDEO | DESIGN | WEB | ETC</p>
            <a href="{% url 'board:index' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">BOARD</button></a>
        </div>
    </div>
{% endblock %}
{% block noauth %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">YUBEEN'S PORTFOLIO</h1>
            <p class="col-md-8 fs-4">PHOTO | VIDEO | DESIGN | WEB | ETC</p>
            <a href="{% url 'acc:login' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">LOGIN</button></a>
        </div>
    </div>
{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block noauth %}
    <div class="container mt-5 mb-5" style="width: 60%;">
        <h1><b>로그인</b></h1>

        <form method="post">
            {% csrf_token %}
            <div class="mt-5">
                <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold;">
                <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold;">
            </div>
            <div class="text-end mt-4">
                <button class="btn btn-dark">LOGIN</button>
            </div>
        </form>
        
    </div>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 60%;">
        <h1><b>프로필</b></h1>

        <div class="text-center mt-5">
            <img src="{{ user.getpic }}" class="rounded-circle" width="250px">
        </div>

        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" disabled value="{{ user.username }}" class="form-control" style="font-weight: bold;" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label class="form-label">AGE</label>
            <input type="text" value="{{ user.age }}" style="font-weight: bold;" disabled class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{ user.comment }}</textarea>
        </div>

        <div class="text-end">
            <a href="{% url 'acc:update' %}" class="btn btn-dark">정보수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                계정삭제
            </button>
        </div>

    </div>


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>계정 삭제 알림</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:delete' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <h5>정말로 삭제하시겠습니까?</h5>
                        <b>패스워드 확인</b> <input type="password" name="ckpw" class="form-control mt-2">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button class="btn btn-danger" style="font-weight: bold; font-family:monospace;">계정삭제</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block noauth %}
    <div class="container mt-5 mb-5" style="width: 60%; font-weight: bold; font-size: 20px;">
        <h1><b>회원가입</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label for="exampleInputEmail1" class="form-label">USERNAME</label>
                <input type="text" name="uname" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
                <input type="password" name="upass" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">AGE</label>
                <input type="number" name="uage" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">COMMENT</label>
                <textarea class="form-control" name="ucomm"></textarea>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">USERPIC</label>
                <input type="file" name="upic" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mt-4 text-end">
                <button type="submit" class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
            </div>
        </form>
    </div>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5"  style="font-size: 20px; font-weight: bold; width: 60%;">
        <h1><b>정보수정</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">USERNAME</label>
                <input type="text" name="uname" value="{{user.username}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
                <input type="password" name="upass" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label class="form-label">AGE</label>
                <input type="number" name="uage" value="{{ user.age }}" class="form-control" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label class="form-label">COMMENT</label>
                <textarea class="form-control" name="ucomm">{{ user.comment }}</textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">USERPIC</label>
                <input type="file" name="upic" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="text-end">
                <a href="{% url 'acc:profile' %}"><button type="button" class="btn btn-dark">BACK</button></a>
                <button class="btn btn-dark">UPDATE</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>PORTFOLIO SITE</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">PROFILE</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'port:index' %}">PORTFOLIO</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">BOARD</a>
                            </li>~
                            
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% block con %}
            {% endblock %}
        {% else %}
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">PROFILE</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'port:index' %}">PORTFOLIO</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% block noauth %}
                <div class="container text-center mt-5">
                    <h1><b>YOU MUST LOGIN TO VIEW THIS PAGE</b></h1>
                    <a href="{% url 'acc:login' %}" class="btn btn-dark mt-5">LOGIN</a>
                </div>
            {% endblock %}
        {% endif %}

        


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
        <h1><b>CREATE</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input name="sub" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea name="con" class="form-control" style="height: 100px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">+</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="width:70%">
        <h1><b>{{ b.subject }}</b></h1>
        <div class="row mt-9">
            <div class="col-lg-15">
                <textarea class="form-control" style="width: 1000px; height:280px;"disabled>{{ b.content }}</textarea>
            </div>
        </div>

        <div class="text-end mt-4">
            {% if b.writer == user %}
                <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    DEL
                </button>
                <a href="{% url 'board:update' b.id %}" class="btn btn-secondary btn-lg">MOD</a>
            {% endif %}
            <a href="{% url 'board:index' %}" class="btn btn-dark btn-lg">BACK</a>
        </div>

        <br><hr>

        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-10">
                    <input type="text" name="com" style="width: 900px;" class="form-control" placeholder="댓글을 남겨주세요">
                </div>
                <div class="col-lg-2 text-end">
                    <button class="btn btn-dark">댓글생성</button>
                </div>
            </div>
        </form>

        <div>
            {% if rset %}
                {% for i in rset %}
                    <div class="row mt-3">
                        <div class="col-lg-2">
                            <img src="{{ i.replyer.getpic }}" width="60%">
                        </div>
                        <div class="col-lg-8">
                            <textarea class="form-control" style="width: 850px; height: 75px;" disabled>{{ i.comment }}</textarea>
                        </div>
                        <div class="text-end mt-3 ">
                            {% if user == i.replyer %}
                                <a href="{% url 'board:dreply' b.id i.id %}"><button class="btn btn-danger btn-sm">댓글삭제</button></a>
                            {% else %}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            {% endif %}
        </div>


    </div>


    <!-- 모달창 -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">게시글 삭제 알림</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말로 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}"><button type="button" class="btn btn-danger">삭제</button></a>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

    <div class="container mt-5" style="width:70%">
        <h1><b>BOARD</b></h1>

        <div class="text-end">
            <a href="{% url 'board:create' %}" class="btn btn-dark">+</a>
        </div>


        <table class="table mt-3 table-hover">
            <thead style="background-color: black; color:white; font-size: 20px;">
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                </tr>
            </thead>
            <tbody>
                {% if bset %}
                    {% for i in bset %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                            <td>{{ i.summary }}</td>
                            <td>{{ i.writer.username }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                {% endif %}
            </tbody>
        </table>

    </div>

    
    <style>
        a.sub {
            text-decoration: none;
            color:black;
            font-weight: bold;
            font-size: 17px;
        }
        a.sub:hover {
            color:gray;
        }
    </style>


{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
        <form method="post">
            {% csrf_token %}
            <h1><b>MOD</b></h1>
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="sub" class="form-control" value="{{ b.subject }}">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ b.writer }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 100px;">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">MOD</button>
            </div> 
        </form>
    </div>
{% endblock %}